"""Create posts table

Revision ID: a76f3c55967b
Revises:
Create Date: 2021-10-16 00:42:45.157701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a76f3c55967b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
                    sa.Column('id',
                              postgresql.UUID(as_uuid=True),
                              nullable=False),
                    sa.Column('title',
                              sa.String(),
                              nullable=True),
                    sa.Column('body',
                              sa.Text(),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id'))

    op.create_index(op.f('ix_posts_id'),
                    'posts',
                    ['id'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_id'),
                  table_name='posts')

    op.drop_table('posts')
    # ### end Alembic commands ###
